main: org.devoxx4kids.TestPlugin
name: SpigotScalaPlugin
version: 0.1
author: xavier
description: 

commands:
   arrow:
      description: This is a demo command.
      usage: /arrow
#      permission: SpigotScalaPlugin.basic
#      permission-message: You don't have <permission>
